dynamics_config:
  _target_: planning_through_contact.planning.planar.planar_plan_config.SliderPusherSystemConfig
  pusher_radius: 0.015
  friction_coeff_table_slider: 0.5
  friction_coeff_slider_pusher: 0.1
  grav_acc: 9.81
  integration_constant: 0.3
  force_scale: 0.01
slider_type: 'tee'
contact_model: ContactModel.kHydroelastic
visualize_desired: true
slider_goal_pose:
  _target_: planning_through_contact.geometry.planar.planar_pose.PlanarPose
  x: 0.575
  y: 0.0
  theta: 0.0
pusher_start_pose:
  _target_: planning_through_contact.geometry.planar.planar_pose.PlanarPose
  x: 0.575
  y: 0.25
  theta: 0.0
time_step: 0.001
closed_loop: false # MPC flag
draw_frames: true
use_realtime: false
delay_before_execution: 5.0
save_plots: false
diffusion_policy_config:
  _target_: planning_through_contact.simulation.controllers.diffusion_policy_source.DiffusionPolicyConfig
  checkpoint: '/home/adam/workspace/gcs-diffusion/data/outputs/push_box_v2/checkpoints/latest.ckpt'
  initial_pusher_pose: ${pusher_start_pose}
  target_slider_pose: ${slider_goal_pose}
  diffusion_policy_path: '/home/adam/workspace/gcs-diffusion'
  freq: 10.0
  delay: ${delay_before_execution}
  debug: false
  device: 'cuda:0'
  cfg_overrides:
    n_action_steps: 8
use_hardware: false
pusher_z_offset: 0.03
camera_configs:
  - name: 'overhead_camera'
    orientation:
      roll: 0.0
      pitch: 2.4347343065320897
      yaw: 3.141592653589793
    position:
      - 1.075
      - 0.0
      - 0.5
    width: 96
    height: 96
    show_rgb: true
collect_data: false
data_dir: 'diffusion_policy_logs'
multi_run_config:
  _target_: planning_through_contact.simulation.planar_pushing.planar_pushing_sim_config.MultiRunConfig
  num_runs: 1
  max_attempt_duration: 90
  seed: 42
  slider_type: ${slider_type}
  pusher_start_pose: ${pusher_start_pose}
  slider_goal_pose: ${slider_goal_pose}
  workspace_width: 0.35
  workspace_height: 0.5

## Robot specific configs
# sim_config
scene_directive_name: 'planar_pushing_iiwa_plant_hydroelastic.yaml'
default_joint_positions: [0.0776, 1.0562, 0.3326, -1.3048, 2.7515, -0.8441, 0.5127,]

# position controller / robot station
robot_station:
  _target_: planning_through_contact.simulation.controllers.iiwa_hardware_station.IiwaHardwareStation
  sim_config: null  # override in hydra.utils.instantiate
  meshcat: null     # override in hydra.utils.instantiate

## Data Collection Config
data_collection_config:
  _target_: 'insert class name here'
